Miscelaneous tweaks for Visual C in Cygwin compatibility

diff --git a/tests/test_env.sh.in b/tests/test_env.sh.in
--- a/tests/test_env.sh.in
+++ b/tests/test_env.sh.in
@@ -1,10 +1,32 @@
-export PATH="$(atf_get_srcdir)/../:${PATH}"
+srcdir="$(atf_get_srcdir)"
+export PATH="$srcdir/..:${PATH}"
+
+#--- begin windows kludge ---
+# When building with Visual Studio, binaries are in a subdirectory named after the configration...
+# and the configuration is not known unless you're in the IDE, or something.
+# So just guess.  This won't work well if you build more than one configuration.
+the_configuration=""
+for configuration in Debug Release RelWithDebInfo
+do
+    if test -d "$srcdir/../$configuration"
+    then
+        if test "$the_configuration" != ""
+        then
+            echo "test_env.sh: FAIL: more than one configuration found"
+            exit 1
+        fi
+        the_configuration=$configuration
+        export PATH="$srcdir/../${configuration}:${PATH}"
+    fi
+done
+#--- end kludge ---
+
 selfdir="@abs_top_srcdir@/tests"
 PATH_SEP=":"
 SYSROOT_DIR="${selfdir}/test"
-if [ "$(uname -s)" = "Msys" ]; then
-	PATH_SEP=";"
-fi
+case "$(uname -s)" in
+Msys|CYGWIN*) PATH_SEP=";";;
+esac
 
 prefix="@prefix@"
 exec_prefix="@exec_prefix@"
